spring.application.name=api-tienda

# --- CONFIGURACIÓN DEL PUERTO (Vital para Render) ---
# Render nos asigna un puerto en la variable PORT. Si no existe, usa 8080.
server.port=${PORT:8080}

# --- BASE DE DATOS ---
# Aquí está el truco: Busca la variable de entorno, si no la halla, usa tu config local.
#Borrar el michi
#spring.datasource.url=jdbc:postgresql://localhost:5432/margarita

# URL: En Render usaremos la variable DB_URL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/margarita}

# USUARIO: En Render usaremos la variable DB_USERNAME
spring.datasource.username=${DB_USERNAME:postgres}

# CONTRASEÑA: En Render usaremos la variable DB_PASSWORD
spring.datasource.password=${DB_PASSWORD:231103}

# --- CONFIGURACIÓN JPA/HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- SUBIDA DE ARCHIVOS ---
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB