spring.application.name=api-tienda

# --- CONFIGURACION DEL PUERTO ---
server.port=${PORT:8081}

# --- BASE DE DATOS ---
# URL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/margarita}
# USUARIO
spring.datasource.username=${DB_USERNAME:postgres}
# PASSWORD
spring.datasource.password=${DB_PASSWORD:231103}

# --- CONFIGURACION JPA/HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- SUBIDA DE ARCHIVOS ---
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# --- CLOUDINARY CONFIG ---
cloudinary.cloud_name=${CLOUDINARY_NAME:demo_cloud}
cloudinary.api_key=${CLOUDINARY_API_KEY:0000000000000}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:demo_secret}